services:
  - type: web
    name: hdotweb-rabbitmq
    plan: starter
    runtime: docker
    envVars:
      - key: RABBITMQ_ERLANG_COOKIE
        generateValue: true
      - key: RABBITMQ_DEFAULT_USER
        value: rabbitmq
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
    disk:
      name: rabbitmq
      mountPath: /var/lib/rabbitmq/mnesia
      sizeGB: 5

  - type: web
    name: hdotweb-rabbitmq-staging
    plan: starter
    runtime: docker
    envVars:
      - key: RABBITMQ_ERLANG_COOKIE
        generateValue: true
      - key: RABBITMQ_DEFAULT_USER
        value: rabbitmq
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
    disk:
      name: rabbitmq-staging
      mountPath: /var/lib/rabbitmq/mnesia
      sizeGB: 5
